In [18]:
import pandas as pd

# Creazione del dataframe(studenti) = dataset(Tabella, Modello, Entity) 
studenti = {
    "nome": ["Mario", "Rudy", "Marco", "Luca", "Giovanni", "Francesco"],
    "cognome": ["Ricci", "Botosso", "Secci", "Bianchi", "Neri", "Rossi"],
    "email": ["mario.ricci@example.info", "rudy.botosso@example.it", "marco.secci@example.com", "luca.bianchi@example.ca", "giovanni.neri@example.com", "francesco.rossi@example.ue"],
    "eta": [30, 54, 54, 28, 35, 42],
    "citta": ["Milano", "Biella", "San Donà di Piave", "Roma", "Napoli", "Torino"],
    "voto": [8, 9, 7, 6, 8, 9],
    "stipendio": [2000, 3000, 1500, 2500, 3500, 4000]
}

# chiama pandas e crea un dataframe a partire dal dizionario studenti
df = pd.DataFrame(studenti)
df # stampa il dataframe(tipo tabella) con i dati degli studenti

,nome,cognome,email,eta,citta,voto,stipendio
0,Mario,Ricci,mario.ricci@example.info,30,Milano,8,2000
1,Rudy,Botosso,rudy.botosso@example.it,54,Biella,9,3000
2,Marco,Secci,marco.secci@example.com,54,San Donà di Piave,7,1500
3,Luca,Bianchi,luca.bianchi@example.ca,28,Roma,6,2500
4,Giovanni,Neri,giovanni.neri@example.com,35,Napoli,8,3500
5,Francesco,Rossi,francesco.rossi@example.ue,42,Torino,9,4000

Filtri in pandas

In [19]:
# select * from dipendenti where stipendio > 2500
df[df["stipendio"] >= 2500] # stampa i dati degli studenti con stipendio maggiore di 2500

,nome,cognome,email,eta,citta,voto,stipendio
1,Rudy,Botosso,rudy.botosso@example.it,54,Biella,9,3000
3,Luca,Bianchi,luca.bianchi@example.ca,28,Roma,6,2500
4,Giovanni,Neri,giovanni.neri@example.com,35,Napoli,8,3500
5,Francesco,Rossi,francesco.rossi@example.ue,42,Torino,9,4000

In [20]:
# select stipendio from dipendenti where nome = 'Giovanni'
df[df["nome"] == "Giovanni"]["stipendio"] # stampa lo stipendio dello studente con nome Giovanni

4    3500
Name: stipendio, dtype: int64

In [21]:
df[df['stipendio'] <= 1500][['nome', 'cognome', 'email']] # stampa nome e cognome degli studenti con stipendio uguale a 1500

    nome cognome                    email
2  Marco   Secci  marco.secci@example.com

In [ ]:
df[df['email'].str.endswith('.ue')] # stampa i dati degli studenti con email che termina con .ue

        nome cognome                       email  eta   citta  voto  stipendio
5  Francesco   Rossi  francesco.rossi@example.ue   42  Torino     9       4000

In [35]:
df[df['citta'].str.contains('an')] # stampa i dati degli studenti con città che contiene la lettera a

,nome,cognome,email,eta,citta,voto,stipendio
0,Mario,Ricci,mario.ricci@example.info,30,Milano,8,2000
2,Marco,Secci,marco.secci@example.com,54,San Donà di Piave,7,1500